In [10]:
# example of horizontal shift image augmentation
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator

In [11]:
from matplotlib import pyplot
import cv2


In [12]:
import os 

listOfFolderName = []

def search(dirname):
    filenames = os.listdir(dirname)
    for filename in filenames:
        #full_filename = os.path.join(dirname, filename)
        listOfFolderName.append(filename)
        print(filenames)

search("C:/Users/user/Desktop/")

['Anaconda Navigator (anaconda3).lnk', 'Chrome Remote Desktop.lnk', 'CNN2020', 'data - 복사본', 'desktop.ini', 'GitHub Desktop.lnk', 'Inside', 'junbeom', 'junbeom_data', 'jun_train_set', 'jun_train_set.zip', 'LeeSac', 'MATLAB Deep Learning Model 만들기.pdf', 'original', 'Outside', 'resize_in1000', 'resize_in500', 'resize_out1000', 'resize_out500', 'temp_img', '재민']
['Anaconda Navigator (anaconda3).lnk', 'Chrome Remote Desktop.lnk', 'CNN2020', 'data - 복사본', 'desktop.ini', 'GitHub Desktop.lnk', 'Inside', 'junbeom', 'junbeom_data', 'jun_train_set', 'jun_train_set.zip', 'LeeSac', 'MATLAB Deep Learning Model 만들기.pdf', 'original', 'Outside', 'resize_in1000', 'resize_in500', 'resize_out1000', 'resize_out500', 'temp_img', '재민']
['Anaconda Navigator (anaconda3).lnk', 'Chrome Remote Desktop.lnk', 'CNN2020', 'data - 복사본', 'desktop.ini', 'GitHub Desktop.lnk', 'Inside', 'junbeom', 'junbeom_data', 'jun_train_set', 'jun_train_set.zip', 'LeeSac', 'MATLAB Deep Learning Model 만들기.pdf', 'original', 'Outside', 

In [15]:
for foldername in listOfFolderName:
    data_path = 'C:/Users/user/Desktop/resize_out500/'
    folder = os.listdir(data_path)
    print(folder)

['IMG_3485.png', 'IMG_3486.png', 'IMG_3487.png', 'IMG_3488.png', 'IMG_3489.png', 'IMG_3490.png', 'IMG_3491.png', 'IMG_3492.png', 'IMG_3493.png', 'IMG_3494.png', 'IMG_3495.png', 'IMG_3496.png', 'IMG_3497.png', 'IMG_3498.png', 'IMG_3499.png', 'IMG_3500.png', 'IMG_3501.png', 'IMG_3502.png', 'IMG_3503.png', 'IMG_3504.png', 'IMG_3505.png', 'IMG_3506.png', 'IMG_3507.png', 'IMG_3508.png', 'IMG_3509.png', 'IMG_3510.png', 'IMG_3511.png', 'IMG_3514.png', 'IMG_3515.png', 'IMG_3516.png', 'IMG_3517.png', 'IMG_3518.png', 'IMG_3519.png', 'IMG_3520.png', 'IMG_3521.png', 'IMG_3522.png', 'IMG_3523.png', 'IMG_3524.png', 'IMG_3525.png', 'IMG_3526.png', 'IMG_3527.png', 'IMG_3528.png', 'IMG_3529.png', 'IMG_3530.png', 'IMG_3531.png', 'IMG_3532.png', 'IMG_3533.png', 'IMG_3534.png', 'IMG_3535.png', 'IMG_3536.png', 'IMG_3537.png', 'IMG_3538.png', 'IMG_3539.png', 'IMG_3540.png', 'IMG_3541.png', 'IMG_3542.png', 'IMG_3641.png', 'IMG_3642.png', 'IMG_3643.png', 'IMG_3644.png', 'IMG_3645.png', 'IMG_3646.png', 'IMG_36

In [16]:
#만들고자하는 갯수
num =9
for file in folder:
    name = file.split(".")[0]
    # load the image
    img = cv2.imread(data_path + name + ".png")
    print(img)
    imageRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # convert to numpy array
    data = img_to_array(img)
    # expand dimension to one sample
    samples = expand_dims(data, 0)
    # create image data augmentation generator
#     datagen = ImageDataGenerator(rotation_range=60, height_shift_range=0.1 )
    datagen = ImageDataGenerator(rotation_range=45, height_shift_range=0.1, width_shift_range=0.1 )

    # prepare iterator
    it = datagen.flow(samples, batch_size=1)
    for i in range(num):   
        batch = it.next()
        # convert to unsigned integers for viewing
        image = batch[0].astype('uint8')
        cv2.imwrite(data_path + name + "test"+ str(i) +".jpg", image)

[[[134 135 115]
  [134 135 115]
  [130 128 110]
  ...
  [193 194 192]
  [172 173 171]
  [192 193 191]]

 [[136 137 117]
  [133 134 114]
  [131 130 112]
  ...
  [171 172 170]
  [197 198 195]
  [184 185 183]]

 [[129 130 110]
  [131 132 112]
  [128 127 109]
  ...
  [192 193 191]
  [193 194 192]
  [190 191 189]]

 ...

 [[160 171 179]
  [141 152 160]
  [143 154 162]
  ...
  [141 153 159]
  [139 152 158]
  [118 130 136]]

 [[143 154 162]
  [150 161 169]
  [152 163 171]
  ...
  [117 129 135]
  [130 142 148]
  [138 150 156]]

 [[150 161 169]
  [ 92 103 111]
  [ 83  94 102]
  ...
  [138 150 156]
  [132 144 150]
  [137 149 155]]]
[[[133 123 105]
  [134 126 107]
  [133 126 106]
  ...
  [194 195 193]
  [193 194 192]
  [177 170 166]]

 [[130 123 104]
  [132 125 106]
  [134 127 108]
  ...
  [193 194 192]
  [203 204 202]
  [198 192 187]]

 [[122 118 100]
  [131 124 105]
  [134 127 108]
  ...
  [181 182 180]
  [195 196 193]
  [199 193 188]]

 ...

 [[125 140 150]
  [173 188 197]
  [133 145 155]
  ..

[[[222 211 189]
  [207 196 174]
  [219 200 179]
  ...
  [232 193 165]
  [233 194 166]
  [234 195 167]]

 [[115 119 108]
  [122 126 114]
  [122 125 110]
  ...
  [232 192 163]
  [233 193 164]
  [233 193 164]]

 [[113 116 100]
  [127 130 114]
  [124 127 112]
  ...
  [231 191 162]
  [232 192 163]
  [232 192 163]]

 ...

 [[149 168 176]
  [142 161 169]
  [171 190 198]
  ...
  [139 152 160]
  [157 174 180]
  [164 180 187]]

 [[138 157 165]
  [133 153 161]
  [122 141 149]
  ...
  [118 131 139]
  [176 194 201]
  [151 167 174]]

 [[145 164 172]
  [149 168 176]
  [138 157 165]
  ...
  [153 165 174]
  [113 129 136]
  [122 138 145]]]
[[[125 125 113]
  [131 132 116]
  [131 132 116]
  ...
  [235 198 172]
  [235 199 172]
  [232 195 169]]

 [[118 118 106]
  [125 126 110]
  [133 135 119]
  ...
  [232 193 165]
  [232 193 165]
  [232 195 167]]

 [[116 116 104]
  [121 122 106]
  [126 127 111]
  ...
  [230 192 160]
  [231 193 163]
  [232 193 165]]

 ...

 [[150 170 177]
  [147 166 174]
  [113 132 140]
  ..

[[[ 39  74  64]
  [ 42  77  67]
  [ 58  87  78]
  ...
  [ 42  48  47]
  [ 27  33  32]
  [ 32  56  56]]

 [[ 45  82  72]
  [ 31  66  56]
  [ 26  60  50]
  ...
  [ 47  53  52]
  [ 25  31  30]
  [ 78  99  97]]

 [[ 62 116 103]
  [ 44  81  71]
  [ 64 106  95]
  ...
  [ 19  24  22]
  [ 27  32  31]
  [ 24  28  28]]

 ...

 [[144 155 160]
  [101 107 112]
  [ 88  86  93]
  ...
  [141 126 117]
  [ 82  65  57]
  [ 83  68  59]]

 [[122 131 138]
  [114 122 129]
  [102 105 113]
  ...
  [ 97  82  73]
  [112 103  89]
  [140 125 116]]

 [[112 120 127]
  [113 121 128]
  [139 153 159]
  ...
  [ 80  68  58]
  [ 86  68  61]
  [ 86  71  62]]]
[[[ 63 128 126]
  [ 84 169 163]
  [ 74 154 149]
  ...
  [244 242 237]
  [253 249 244]
  [ 82  63  60]]

 [[ 69 135 129]
  [ 72 145 140]
  [ 66 130 128]
  ...
  [ 91 115 116]
  [ 88 114 115]
  [ 32  31  40]]

 [[110 176 169]
  [ 54 121 114]
  [136 223 214]
  ...
  [129 168 167]
  [ 64  97  99]
  [ 88 107 115]]

 ...

 [[138 149 156]
  [114 120 125]
  [128 134 139]
  ..

[[[ 31  73  62]
  [ 47 101  93]
  [ 72 158 148]
  ...
  [254 254 246]
  [157 104 122]
  [211 218 215]]

 [[ 35  64  55]
  [ 47  81  75]
  [ 43 107  98]
  ...
  [254 255 245]
  [200 153 167]
  [196 214 216]]

 [[ 56  85  76]
  [ 43  72  66]
  [ 57  94  89]
  ...
  [255 255 246]
  [254 230 238]
  [165 173 179]]

 ...

 [[140 150 157]
  [118 128 135]
  [129 141 147]
  ...
  [ 61  48  40]
  [ 96  83  75]
  [ 71  58  50]]

 [[116 123 132]
  [147 157 164]
  [153 164 170]
  ...
  [ 73  60  52]
  [ 69  56  48]
  [116 103  95]]

 [[112 119 128]
  [151 162 168]
  [166 182 188]
  ...
  [ 89  76  68]
  [ 75  61  54]
  [136 123 115]]]
[[[ 45 104  95]
  [ 64 135 124]
  [ 18  74  70]
  ...
  [240 208 214]
  [190 189 191]
  [250 255 245]]

 [[ 39  83  76]
  [113 182 171]
  [ 66 139 132]
  ...
  [255 251 250]
  [135 133 141]
  [216 230 226]]

 [[ 28  58  53]
  [ 38  76  69]
  [ 89 173 164]
  ...
  [254 254 250]
  [120  93 107]
  [221 220 219]]

 ...

 [[118 126 133]
  [113 121 127]
  [108 120 126]
  ..

[[[165 133 113]
  [163 130 110]
  [161 125 102]
  ...
  [236 198 174]
  [236 198 174]
  [234 196 172]]

 [[166 134 115]
  [164 133 112]
  [163 130 107]
  ...
  [235 194 171]
  [236 198 174]
  [235 197 173]]

 [[165 136 117]
  [165 134 114]
  [162 131 110]
  ...
  [235 194 171]
  [237 197 174]
  [236 198 174]]

 ...

 [[ 62  48  42]
  [ 41  27  21]
  [ 48  34  28]
  ...
  [ 55  41  35]
  [ 45  33  27]
  [ 55  43  37]]

 [[ 66  52  46]
  [ 63  49  43]
  [ 53  39  34]
  ...
  [ 58  44  38]
  [ 54  42  36]
  [ 51  39  33]]

 [[ 70  56  50]
  [ 66  52  46]
  [ 56  42  36]
  ...
  [ 33  19  13]
  [ 48  36  30]
  [ 47  35  30]]]
[[[226 182 158]
  [227 181 157]
  [225 180 154]
  ...
  [243 203 178]
  [244 204 179]
  [243 203 178]]

 [[228 180 156]
  [227 179 155]
  [226 179 152]
  ...
  [246 206 181]
  [245 205 180]
  [243 203 178]]

 [[228 180 156]
  [227 179 154]
  [227 179 152]
  ...
  [243 203 178]
  [239 199 174]
  [235 195 170]]

 ...

 [[ 36  21  19]
  [ 48  33  31]
  [ 67  53  47]
  ..

[[[ 52  67  61]
  [ 14  29  22]
  [  7  19  13]
  ...
  [159 196 180]
  [161 198 182]
  [163 200 184]]

 [[ 19  37  30]
  [ 28  46  39]
  [  2  15   9]
  ...
  [159 196 180]
  [160 197 181]
  [162 199 183]]

 [[ 17  38  30]
  [ 28  49  41]
  [ 14  32  25]
  ...
  [160 197 181]
  [160 197 181]
  [161 198 182]]

 ...

 [[ 82  66  68]
  [ 87  72  76]
  [ 87  72  76]
  ...
  [ 97  73  61]
  [ 90  66  54]
  [154 130 111]]

 [[ 91  74  77]
  [106  92  98]
  [ 95  80  84]
  ...
  [123  99  87]
  [111  87  74]
  [ 78  52  40]]

 [[122  99  97]
  [ 93  76  82]
  [ 81  66  70]
  ...
  [106  81  71]
  [139 116 101]
  [122  99  85]]]
[[[ 37  54  43]
  [ 65  79  68]
  [ 69  83  72]
  ...
  [175 214 199]
  [174 213 198]
  [173 212 197]]

 [[ 57  67  57]
  [ 60  66  57]
  [ 73  85  75]
  ...
  [175 214 199]
  [175 214 199]
  [174 213 198]]

 [[ 45  61  50]
  [ 61  71  61]
  [102 125 112]
  ...
  [175 214 199]
  [175 214 199]
  [174 213 198]]

 ...

 [[112  89  93]
  [128 105 109]
  [103  80  85]
  ..

[[[223 254 236]
  [163 199 179]
  [198 236 214]
  ...
  [103 223 198]
  [105 225 200]
  [102 222 197]]

 [[190 213 195]
  [186 213 194]
  [194 233 211]
  ...
  [102 222 197]
  [102 223 197]
  [103 223 198]]

 [[126 147 135]
  [ 82 104  90]
  [ 69  99  84]
  ...
  [102 222 197]
  [102 222 197]
  [103 223 198]]

 ...

 [[ 65  52  56]
  [ 83  69  73]
  [ 77  63  67]
  ...
  [154 136 128]
  [111  93  84]
  [147 129 118]]

 [[ 69  55  60]
  [ 85  71  75]
  [ 76  62  66]
  ...
  [130 112 105]
  [135 117 108]
  [149 132 119]]

 [[ 77  63  67]
  [ 72  58  62]
  [ 79  65  69]
  ...
  [132 114 107]
  [170 152 143]
  [135 117 106]]]
[[[ 16  54  44]
  [ 21  44  25]
  [ 14  33   8]
  ...
  [101 222 194]
  [ 99 220 192]
  [ 98 220 191]]

 [[ 34  68  55]
  [ 30  53  33]
  [ 23  43   2]
  ...
  [100 221 193]
  [100 221 193]
  [ 98 219 191]]

 [[ 47  76  62]
  [ 47  67  54]
  [ 23  43   3]
  ...
  [101 222 194]
  [100 221 193]
  [ 97 218 190]]

 ...

 [[ 69  55  59]
  [ 81  67  71]
  [ 78  64  68]
  ..

[[[ 16  57  42]
  [ 17  58  42]
  [ 40  85  69]
  ...
  [ 99 228 199]
  [101 230 201]
  [103 232 203]]

 [[ 20  57  42]
  [ 18  48  35]
  [ 15  53  39]
  ...
  [104 233 204]
  [103 232 203]
  [105 234 205]]

 [[  4  41  26]
  [ 17  47  34]
  [ 10  43  29]
  ...
  [104 233 204]
  [104 233 204]
  [103 232 203]]

 ...

 [[104  84  89]
  [ 94  74  79]
  [ 94  74  79]
  ...
  [108  83  73]
  [146 120 109]
  [128 101  90]]

 [[ 98  78  83]
  [ 98  78  83]
  [113  93  98]
  ...
  [ 98  73  63]
  [102  77  62]
  [115  87  75]]

 [[101  81  86]
  [103  83  88]
  [ 94  74  79]
  ...
  [118  89  80]
  [126  98  84]
  [174 146 129]]]
[[[ 13  36  22]
  [ 63 106  80]
  [ 11  32  19]
  ...
  [ 99 226 200]
  [ 98 225 199]
  [ 98 225 199]]

 [[ 21  42  27]
  [ 29  51  39]
  [  5  27  15]
  ...
  [ 97 224 198]
  [ 98 225 199]
  [ 99 226 200]]

 [[ 12  30  19]
  [ 24  45  36]
  [ 68 104  90]
  ...
  [ 98 225 199]
  [ 97 224 198]
  [ 97 224 198]]

 ...

 [[ 83  69  72]
  [ 78  63  67]
  [ 85  70  74]
  ..

[[[112  79  76]
  [248 236 218]
  [239 232 222]
  ...
  [ 57  81  81]
  [ 43  61  62]
  [ 31  51  53]]

 [[234 233 218]
  [224 220 201]
  [215 221 204]
  ...
  [ 41  62  64]
  [ 33  54  56]
  [ 13  36  38]]

 [[213 211 196]
  [103 102  97]
  [116 129 127]
  ...
  [ 32  55  57]
  [ 51  72  73]
  [ 29  50  52]]

 ...

 [[222 235 237]
  [217 230 232]
  [219 232 234]
  ...
  [ 94  76  65]
  [ 98  80  69]
  [ 62  44  35]]

 [[230 243 245]
  [220 233 235]
  [212 225 227]
  ...
  [119 101  90]
  [ 86  68  57]
  [121 102  95]]

 [[241 253 254]
  [225 238 240]
  [214 227 229]
  ...
  [104  86  75]
  [ 96  78  67]
  [ 86  68  57]]]
[[[ 56  79  71]
  [ 36  49  43]
  [ 71  68  64]
  ...
  [ 25  58  61]
  [ 45  78  81]
  [ 68  92  97]]

 [[ 82 107  94]
  [ 56  77  68]
  [144 141 138]
  ...
  [ 68 101 104]
  [ 47  80  83]
  [166 192 196]]

 [[ 81  94  84]
  [ 80 106  96]
  [ 64  68  62]
  ...
  [ 71 127 128]
  [122 177 178]
  [ 91 131 133]]

 ...

 [[225 238 240]
  [232 245 247]
  [236 249 251]
  ..

[[[141 103 109]
  [154 135 132]
  [111  77  87]
  ...
  [ 47  75  76]
  [106 134 135]
  [ 47  75  76]]

 [[187 143 150]
  [194 197 186]
  [120  93  95]
  ...
  [ 78 101 103]
  [ 93 118 120]
  [ 72 100 101]]

 [[158  92 101]
  [205 199 191]
  [202 174 174]
  ...
  [ 71  82  86]
  [126 136 140]
  [ 72  96  98]]

 ...

 [[238 251 253]
  [231 244 246]
  [201 212 216]
  ...
  [119 102  91]
  [143 126 113]
  [156 140 125]]

 [[212 221 224]
  [201 213 215]
  [199 207 214]
  ...
  [110  92  82]
  [ 87  71  55]
  [110  94  78]]

 [[214 227 229]
  [233 246 248]
  [235 247 249]
  ...
  [107  89  80]
  [109  91  80]
  [142 126 110]]]
[[[166 146 141]
  [218 197 197]
  [114  86  90]
  ...
  [ 64  70  69]
  [100 106 105]
  [ 99 105 104]]

 [[255 255 249]
  [250 238 229]
  [223 201 205]
  ...
  [103  93  86]
  [162 150 148]
  [ 65  61  60]]

 [[254 254 248]
  [245 233 223]
  [245 241 233]
  ...
  [234 251 244]
  [250 253 248]
  [217 218 216]]

 ...

 [[211 223 225]
  [236 248 250]
  [243 254 255]
  ..

[[[ 37  61  52]
  [ 25  55  46]
  [110 160 147]
  ...
  [228 220 214]
  [106  90  99]
  [ 71  80  83]]

 [[ 50  84  74]
  [ 27  60  46]
  [ 30  64  54]
  ...
  [ 70  60  70]
  [ 82  71  84]
  [161 168 171]]

 [[ 24  57  47]
  [ 22  54  41]
  [ 33  65  54]
  ...
  [ 51  54  63]
  [238 255 253]
  [ 84  73  77]]

 ...

 [[211 223 225]
  [211 223 225]
  [215 227 230]
  ...
  [121 101  90]
  [ 83  65  56]
  [103  85  76]]

 [[208 220 222]
  [224 236 238]
  [185 192 195]
  ...
  [152 130 119]
  [109  90  82]
  [107  89  80]]

 [[214 226 228]
  [230 242 244]
  [242 254 255]
  ...
  [115  93  82]
  [ 76  57  43]
  [102  83  70]]]
[[[ 36  65  56]
  [ 34  63  54]
  [ 90 124 114]
  ...
  [240 224 216]
  [ 68  73  77]
  [ 68  81  83]]

 [[ 30  59  50]
  [ 39  68  59]
  [ 44  73  64]
  ...
  [109  86  98]
  [ 94  86  91]
  [151 171 167]]

 [[ 35  64  55]
  [ 36  65  56]
  [ 30  57  48]
  ...
  [ 34  32  40]
  [237 255 254]
  [106  97  94]]

 ...

 [[210 222 224]
  [185 190 193]
  [242 254 254]
  ..