In [10]:
# example of horizontal shift image augmentation
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator

In [11]:
from matplotlib import pyplot
import cv2


In [12]:
import os 

listOfFolderName = []

def search(dirname):
    filenames = os.listdir(dirname)
    for filename in filenames:
        #full_filename = os.path.join(dirname, filename)
        listOfFolderName.append(filename)
        print(filenames)

search("C:/Users/user/Desktop/")

['Anaconda Navigator (anaconda3).lnk', 'Chrome Remote Desktop.lnk', 'CNN2020', 'data - 복사본', 'desktop.ini', 'GitHub Desktop.lnk', 'Inside', 'junbeom', 'junbeom_data', 'jun_train_set', 'jun_train_set.zip', 'LeeSac', 'MATLAB Deep Learning Model 만들기.pdf', 'original', 'Outside', 'resize_in1000', 'resize_in500', 'resize_out1000', 'resize_out500', 'temp_img', '재민']
['Anaconda Navigator (anaconda3).lnk', 'Chrome Remote Desktop.lnk', 'CNN2020', 'data - 복사본', 'desktop.ini', 'GitHub Desktop.lnk', 'Inside', 'junbeom', 'junbeom_data', 'jun_train_set', 'jun_train_set.zip', 'LeeSac', 'MATLAB Deep Learning Model 만들기.pdf', 'original', 'Outside', 'resize_in1000', 'resize_in500', 'resize_out1000', 'resize_out500', 'temp_img', '재민']
['Anaconda Navigator (anaconda3).lnk', 'Chrome Remote Desktop.lnk', 'CNN2020', 'data - 복사본', 'desktop.ini', 'GitHub Desktop.lnk', 'Inside', 'junbeom', 'junbeom_data', 'jun_train_set', 'jun_train_set.zip', 'LeeSac', 'MATLAB Deep Learning Model 만들기.pdf', 'original', 'Outside', 

In [13]:
for foldername in listOfFolderName:
    data_path = 'C:/Users/user/Desktop/resize_out1000/'
    folder = os.listdir(data_path)
    print(folder)

['IMG_3485.png', 'IMG_3486.png', 'IMG_3487.png', 'IMG_3488.png', 'IMG_3489.png', 'IMG_3490.png', 'IMG_3491.png', 'IMG_3492.png', 'IMG_3493.png', 'IMG_3494.png', 'IMG_3495.png', 'IMG_3496.png', 'IMG_3497.png', 'IMG_3498.png', 'IMG_3499.png', 'IMG_3500.png', 'IMG_3501.png', 'IMG_3502.png', 'IMG_3503.png', 'IMG_3504.png', 'IMG_3505.png', 'IMG_3506.png', 'IMG_3507.png', 'IMG_3508.png', 'IMG_3509.png', 'IMG_3510.png', 'IMG_3511.png', 'IMG_3514.png', 'IMG_3515.png', 'IMG_3516.png', 'IMG_3517.png', 'IMG_3518.png', 'IMG_3519.png', 'IMG_3520.png', 'IMG_3521.png', 'IMG_3522.png', 'IMG_3523.png', 'IMG_3524.png', 'IMG_3525.png', 'IMG_3526.png', 'IMG_3527.png', 'IMG_3528.png', 'IMG_3529.png', 'IMG_3530.png', 'IMG_3531.png', 'IMG_3532.png', 'IMG_3533.png', 'IMG_3534.png', 'IMG_3535.png', 'IMG_3536.png', 'IMG_3537.png', 'IMG_3538.png', 'IMG_3539.png', 'IMG_3540.png', 'IMG_3541.png', 'IMG_3542.png', 'IMG_3641.png', 'IMG_3642.png', 'IMG_3643.png', 'IMG_3644.png', 'IMG_3645.png', 'IMG_3646.png', 'IMG_36

In [ ]:
#만들고자하는 갯수
num =9
for file in folder:
    name = file.split(".")[0]
    # load the image
    img = cv2.imread(data_path + name + ".png")
    print(img)
    imageRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # convert to numpy array
    data = img_to_array(img)
    # expand dimension to one sample
    samples = expand_dims(data, 0)
    # create image data augmentation generator
#     datagen = ImageDataGenerator(rotation_range=60, height_shift_range=0.1 )
    datagen = ImageDataGenerator(rotation_range=45, height_shift_range=0.1, width_shift_range=0.1 )

    # prepare iterator
    it = datagen.flow(samples, batch_size=1)
    for i in range(num):   
        batch = it.next()
        # convert to unsigned integers for viewing
        image = batch[0].astype('uint8')
        cv2.imwrite(data_path + name + "test"+ str(i) +".jpg", image)

[[[131 132 112]
  [132 133 113]
  [133 134 114]
  ...
  [172 173 171]
  [177 178 176]
  [188 189 187]]

 [[134 135 115]
  [134 135 115]
  [134 135 115]
  ...
  [192 194 191]
  [195 196 195]
  [183 184 182]]

 [[133 134 114]
  [136 137 117]
  [134 135 115]
  ...
  [193 193 191]
  [193 194 192]
  [185 186 184]]

 ...

 [[150 161 169]
  [159 170 178]
  [151 162 170]
  ...
  [116 128 134]
  [115 127 133]
  [109 121 126]]

 [[155 166 174]
  [168 179 187]
  [128 138 147]
  ...
  [131 143 149]
  [131 143 149]
  [132 143 148]]

 [[153 163 170]
  [106 116 123]
  [ 82  92  99]
  ...
  [156 167 171]
  [149 160 164]
  [163 173 176]]]
[[[133 123 105]
  [133 123 106]
  [134 125 107]
  ...
  [196 197 195]
  [205 203 197]
  [205 196 192]]

 [[132 122 104]
  [132 121 104]
  [132 124 106]
  ...
  [197 198 196]
  [201 199 194]
  [184 175 171]]

 [[131 124 105]
  [132 123 105]
  [131 123 104]
  ...
  [203 203 201]
  [169 167 161]
  [194 185 181]]

 ...

 [[148 160 170]
  [127 138 148]
  [129 139 149]
  ..

[[[233 220 194]
  [234 221 195]
  [221 208 182]
  ...
  [233 194 166]
  [234 195 167]
  [236 198 171]]

 [[144 140 122]
  [147 144 125]
  [150 146 128]
  ...
  [233 194 166]
  [234 195 167]
  [233 195 168]]

 [[118 119 105]
  [137 137 123]
  [139 139 125]
  ...
  [234 194 166]
  [234 194 166]
  [232 192 166]]

 ...

 [[141 160 168]
  [143 162 170]
  [147 166 174]
  ...
  [198 220 226]
  [196 214 221]
  [158 174 180]]

 [[135 154 162]
  [150 169 177]
  [153 172 180]
  ...
  [154 173 180]
  [111 127 134]
  [152 167 174]]

 [[131 149 156]
  [134 152 159]
  [152 170 177]
  ...
  [ 55  67  73]
  [ 68  80  86]
  [159 170 175]]]
[[[132 128 117]
  [127 123 111]
  [119 116 102]
  ...
  [235 198 172]
  [234 197 171]
  [236 199 174]]

 [[120 122 110]
  [119 122 108]
  [127 130 114]
  ...
  [233 196 170]
  [232 195 169]
  [233 197 172]]

 [[118 120 108]
  [118 121 107]
  [121 124 108]
  ...
  [234 194 169]
  [231 194 168]
  [232 195 170]]

 ...

 [[192 212 220]
  [197 216 224]
  [163 181 189]
  ..

[[[ 36  71  61]
  [ 36  71  61]
  [ 44  79  69]
  ...
  [ 24  34  32]
  [ 40  64  64]
  [ 43  66  65]]

 [[ 44  79  69]
  [ 43  77  67]
  [ 58  93  83]
  ...
  [ 33  43  41]
  [ 33  57  57]
  [ 55  78  77]]

 [[ 44  79  70]
  [ 58  93  83]
  [ 71 106  96]
  ...
  [ 19  29  27]
  [ 46  69  69]
  [ 64  87  86]]

 ...

 [[120 129 136]
  [118 126 132]
  [112 120 127]
  ...
  [101  91  81]
  [108  93  84]
  [ 86  72  64]]

 [[128 136 143]
  [120 128 135]
  [112 120 127]
  ...
  [ 73  61  51]
  [ 83  68  59]
  [ 85  71  62]]

 [[107 113 119]
  [104 110 115]
  [104 110 115]
  ...
  [ 97  81  74]
  [ 77  64  56]
  [ 75  63  56]]]
[[[ 72 137 135]
  [ 61 126 124]
  [ 58 134 130]
  ...
  [254 247 243]
  [217 209 204]
  [ 61  50  47]]

 [[ 70 135 133]
  [ 83 148 146]
  [126 208 203]
  ...
  [252 250 246]
  [226 218 213]
  [ 72  61  57]]

 [[ 74 140 137]
  [ 83 148 145]
  [ 92 167 162]
  ...
  [221 222 217]
  [ 89  81  78]
  [ 56  45  43]]

 ...

 [[151 164 172]
  [138 142 151]
  [113 119 128]
  ..

[[[ 43  89  77]
  [ 41  87  75]
  [ 45 100  91]
  ...
  [125  94 109]
  [216 220 218]
  [250 254 246]]

 [[ 32  69  59]
  [ 32  69  59]
  [ 62 102  96]
  ...
  [161 124 140]
  [201 209 212]
  [241 251 249]]

 [[ 45  79  69]
  [ 22  56  46]
  [ 27  60  54]
  ...
  [175 134 151]
  [181 190 196]
  [222 235 234]]

 ...

 [[116 123 132]
  [149 156 165]
  [144 150 158]
  ...
  [ 54  41  33]
  [105  92  84]
  [ 92  80  73]]

 [[130 137 146]
  [118 125 134]
  [121 126 134]
  ...
  [ 64  51  43]
  [ 91  77  70]
  [117 105  97]]

 [[132 138 145]
  [116 122 129]
  [129 133 138]
  ...
  [ 76  64  58]
  [ 86  74  68]
  [102  90  85]]]
[[[ 63 125 115]
  [ 53 123 112]
  [ 88 171 157]
  ...
  [190 195 192]
  [248 255 240]
  [250 255 243]]

 [[ 22  68  61]
  [ 29  83  73]
  [ 98 166 155]
  ...
  [207 211 209]
  [249 252 247]
  [252 255 251]]

 [[ 17  57  51]
  [ 49  97  89]
  [  0  56  46]
  ...
  [202 207 204]
  [240 243 241]
  [186 190 188]]

 ...

 [[202 217 217]
  [195 210 210]
  [139 147 154]
  ..

[[[168 136 117]
  [163 130 110]
  [162 129 109]
  ...
  [237 199 175]
  [235 197 173]
  [234 196 173]]

 [[167 135 116]
  [164 132 112]
  [164 131 111]
  ...
  [236 198 174]
  [233 195 171]
  [233 195 172]]

 [[167 135 116]
  [166 135 114]
  [165 132 112]
  ...
  [235 197 173]
  [234 196 172]
  [232 195 172]]

 ...

 [[ 71  57  51]
  [ 65  51  45]
  [ 72  58  52]
  ...
  [ 65  53  47]
  [ 50  38  32]
  [ 54  43  38]]

 [[ 72  58  52]
  [ 68  54  48]
  [ 65  51  45]
  ...
  [ 45  32  26]
  [ 50  38  32]
  [ 58  46  41]]

 [[ 59  47  43]
  [ 66  54  50]
  [ 68  56  52]
  ...
  [ 43  32  28]
  [ 45  34  30]
  [ 52  42  38]]]
[[[227 183 159]
  [226 182 158]
  [226 182 158]
  ...
  [241 201 176]
  [240 200 175]
  [242 203 178]]

 [[227 181 157]
  [227 181 157]
  [226 180 156]
  ...
  [246 206 181]
  [244 204 179]
  [244 205 181]]

 [[226 180 156]
  [226 180 156]
  [225 179 155]
  ...
  [246 206 181]
  [244 204 179]
  [243 204 180]]

 ...

 [[ 46  31  29]
  [ 38  23  21]
  [ 30  15  14]
  ..

[[[ 51  67  60]
  [ 46  62  55]
  [ 21  37  30]
  ...
  [162 199 183]
  [163 200 184]
  [164 200 185]]

 [[ 43  59  52]
  [ 48  64  57]
  [ 26  42  35]
  ...
  [162 199 183]
  [162 199 183]
  [163 199 184]]

 [[ 25  43  36]
  [ 22  40  33]
  [ 31  49  42]
  ...
  [161 198 182]
  [162 199 183]
  [162 198 183]]

 ...

 [[ 95  74  83]
  [116  96 104]
  [111  97 100]
  ...
  [103  79  64]
  [ 96  64  58]
  [ 93  62  56]]

 [[117  96  98]
  [108  87  90]
  [100  84  92]
  ...
  [112  87  73]
  [141 112 103]
  [107  78  70]]

 [[170 148 142]
  [171 149 143]
  [102  84  82]
  ...
  [106  82  71]
  [137 117 102]
  [151 133 119]]]
[[[ 41  61  49]
  [ 53  70  59]
  [ 57  73  62]
  ...
  [174 213 198]
  [173 212 197]
  [174 211 198]]

 [[ 52  68  56]
  [ 59  72  61]
  [ 48  58  48]
  ...
  [174 213 198]
  [174 213 198]
  [174 211 198]]

 [[ 63  74  64]
  [ 52  62  52]
  [ 51  60  49]
  ...
  [174 213 198]
  [174 213 198]
  [175 213 199]]

 ...

 [[113  89  93]
  [116  93  97]
  [118  94  99]
  ..

[[[220 253 236]
  [195 224 208]
  [168 199 183]
  ...
  [104 224 199]
  [103 222 197]
  [103 221 197]]

 [[205 237 217]
  [221 255 236]
  [201 238 218]
  ...
  [104 224 199]
  [103 223 198]
  [103 222 197]]

 [[163 189 169]
  [180 212 191]
  [189 224 202]
  ...
  [103 223 198]
  [103 223 198]
  [104 222 198]]

 ...

 [[ 70  57  61]
  [ 75  61  65]
  [ 80  66  70]
  ...
  [123 105  95]
  [178 160 149]
  [124 107  97]]

 [[ 70  56  60]
  [ 80  66  71]
  [ 82  68  72]
  ...
  [156 138 128]
  [202 184 173]
  [144 127 117]]

 [[ 76  65  68]
  [ 76  65  68]
  [ 69  58  61]
  ...
  [164 147 140]
  [126 108 101]
  [110  93  87]]]
[[[  7  43  36]
  [ 14  52  42]
  [ 10  37  32]
  ...
  [ 99 220 192]
  [ 99 220 192]
  [100 219 193]]

 [[ 43  79  65]
  [ 23  58  52]
  [  8  36  26]
  ...
  [100 221 193]
  [ 99 220 192]
  [ 98 217 191]]

 [[ 41  74  63]
  [ 35  70  62]
  [ 14  42  32]
  ...
  [100 221 193]
  [100 221 193]
  [ 98 217 191]]

 ...

 [[ 83  69  73]
  [ 77  63  67]
  [ 79  65  69]
  ..