In [1]:
# example of horizontal shift image augmentation
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator

Using TensorFlow backend.
C:\Users\user\anaconda3\envs\Mask-R-CNN-DEMO-tf-150\lib\site-packages\tensorflow\python\framework\dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\user\anaconda3\envs\Mask-R-CNN-DEMO-tf-150\lib\site-packages\tensorflow\python\framework\dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\user\anaconda3\envs\Mask-R-CNN-DEMO-tf-150\lib\site-packages\tensorflow\python\framework\dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])

In [2]:
from matplotlib import pyplot
import cv2


In [4]:
import os 

listOfFolderName = []

def search(dirname):
    filenames = os.listdir(dirname)
    for filename in filenames:
        #full_filename = os.path.join(dirname, filename)
        listOfFolderName.append(filename)
        print(filenames)

search("C:/Users/user/Desktop/")

['Anaconda Navigator (anaconda3).lnk', 'Chrome Remote Desktop.lnk', 'CNN2020', 'data - 복사본', 'desktop.ini', 'GitHub Desktop.lnk', 'Inside', 'junbeom', 'junbeom_data', 'jun_train_set', 'jun_train_set.zip', 'LeeSac', 'MATLAB Deep Learning Model 만들기.pdf', 'original', 'Outside', 'resize_in1000', 'resize_in500', 'resize_out1000', 'resize_out500', 'temp_img', '재민']
['Anaconda Navigator (anaconda3).lnk', 'Chrome Remote Desktop.lnk', 'CNN2020', 'data - 복사본', 'desktop.ini', 'GitHub Desktop.lnk', 'Inside', 'junbeom', 'junbeom_data', 'jun_train_set', 'jun_train_set.zip', 'LeeSac', 'MATLAB Deep Learning Model 만들기.pdf', 'original', 'Outside', 'resize_in1000', 'resize_in500', 'resize_out1000', 'resize_out500', 'temp_img', '재민']
['Anaconda Navigator (anaconda3).lnk', 'Chrome Remote Desktop.lnk', 'CNN2020', 'data - 복사본', 'desktop.ini', 'GitHub Desktop.lnk', 'Inside', 'junbeom', 'junbeom_data', 'jun_train_set', 'jun_train_set.zip', 'LeeSac', 'MATLAB Deep Learning Model 만들기.pdf', 'original', 'Outside', 

In [8]:
for foldername in listOfFolderName:
    data_path = 'C:/Users/user/Desktop/resize_in1000/'
    folder = os.listdir(data_path)
    print(folder)

['IMG_3445.png', 'IMG_3446.png', 'IMG_3447.png', 'IMG_3448.png', 'IMG_3449.png', 'IMG_3450.png', 'IMG_3451.png', 'IMG_3452.png', 'IMG_3453.png', 'IMG_3454.png', 'IMG_3455.png', 'IMG_3456.png', 'IMG_3457.png', 'IMG_3458.png', 'IMG_3459.png', 'IMG_3460.png', 'IMG_3461.png', 'IMG_3462.png', 'IMG_3463.png', 'IMG_3464.png', 'IMG_3465.png', 'IMG_3466.png', 'IMG_3467.png', 'IMG_3468.png', 'IMG_3469.png', 'IMG_3470.png', 'IMG_3471.png', 'IMG_3472.png', 'IMG_3473.png', 'IMG_3474.png', 'IMG_3475.png', 'IMG_3476.png', 'IMG_3477.png', 'IMG_3478.png', 'IMG_3479.png', 'IMG_3480.png', 'IMG_3481.png', 'IMG_3482.png', 'IMG_3483.png', 'IMG_3484.png', 'IMG_3543.png', 'IMG_3544.png', 'IMG_3545.png', 'IMG_3546.png', 'IMG_3547.png', 'IMG_3548.png', 'IMG_3549.png', 'IMG_3550.png', 'IMG_3551.png', 'IMG_3552.png', 'IMG_3553.png', 'IMG_3554.png', 'IMG_3555.png', 'IMG_3556.png', 'IMG_3557.png', 'IMG_3558.png', 'IMG_3559.png', 'IMG_3560.png', 'IMG_3561.png', 'IMG_3562.png', 'IMG_3563.png', 'IMG_3564.png', 'IMG_35

In [ ]:
#만들고자하는 갯수
num =9
for file in folder:
    name = file.split(".")[0]
    # load the image
    img = cv2.imread(data_path + name + ".png")
    print(img)
    imageRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # convert to numpy array
    data = img_to_array(img)
    # expand dimension to one sample
    samples = expand_dims(data, 0)
    # create image data augmentation generator
#     datagen = ImageDataGenerator(rotation_range=60, height_shift_range=0.1 )
    datagen = ImageDataGenerator(rotation_range=45, height_shift_range=0.1, width_shift_range=0.1 )

    # prepare iterator
    it = datagen.flow(samples, batch_size=1)
    for i in range(num):   
        batch = it.next()
        # convert to unsigned integers for viewing
        image = batch[0].astype('uint8')
        cv2.imwrite(data_path + name + "test"+ str(i) +".jpg", image)

[[[233 200 180]
  [233 200 180]
  [232 199 179]
  ...
  [249 228 216]
  [254 235 222]
  [251 234 222]]

 [[234 201 181]
  [234 201 181]
  [233 200 180]
  ...
  [252 231 219]
  [254 235 222]
  [251 235 222]]

 [[234 201 181]
  [234 201 181]
  [234 201 181]
  ...
  [253 233 220]
  [254 235 222]
  [252 235 223]]

 ...

 [[129 139 146]
  [128 139 145]
  [123 133 140]
  ...
  [146 158 160]
  [146 158 161]
  [133 144 145]]

 [[127 137 144]
  [123 133 140]
  [125 135 142]
  ...
  [133 146 147]
  [140 152 154]
  [132 143 144]]

 [[135 144 148]
  [142 151 155]
  [135 144 148]
  ...
  [123 134 134]
  [141 151 151]
  [163 172 172]]]
[[[234 205 184]
  [234 206 185]
  [236 207 186]
  ...
  [252 234 222]
  [248 231 218]
  [247 231 218]]

 [[237 208 187]
  [238 209 188]
  [239 210 189]
  ...
  [251 233 223]
  [250 231 221]
  [248 230 220]]

 [[238 209 188]
  [239 210 189]
  [240 211 190]
  ...
  [251 230 222]
  [251 230 222]
  [250 230 221]]

 ...

 [[155 164 173]
  [148 157 166]
  [131 144 152]
  ..

[[[236 205 184]
  [236 205 184]
  [235 204 183]
  ...
  [232 212 195]
  [234 214 197]
  [228 208 192]]

 [[236 205 184]
  [236 205 184]
  [234 203 182]
  ...
  [230 210 193]
  [231 211 194]
  [226 206 190]]

 [[235 204 183]
  [234 203 182]
  [232 201 180]
  ...
  [229 209 192]
  [231 211 194]
  [228 209 193]]

 ...

 [[132 138 149]
  [115 124 134]
  [111 118 129]
  ...
  [141 149 166]
  [124 133 150]
  [122 130 146]]

 [[120 126 137]
  [108 118 128]
  [147 156 166]
  ...
  [113 121 138]
  [125 133 150]
  [127 135 151]]

 [[141 149 158]
  [137 147 155]
  [133 146 154]
  ...
  [121 128 143]
  [125 133 147]
  [131 137 151]]]
[[[241 211 192]
  [241 211 192]
  [239 209 190]
  ...
  [249 233 224]
  [248 232 220]
  [244 228 218]]

 [[238 208 189]
  [237 207 188]
  [237 207 188]
  ...
  [246 231 223]
  [246 231 219]
  [244 229 218]]

 [[236 206 187]
  [236 206 187]
  [237 207 188]
  ...
  [246 231 222]
  [245 231 219]
  [243 228 218]]

 ...

 [[122 130 143]
  [143 151 164]
  [127 135 148]
  ..

[[[223 184 162]
  [223 184 162]
  [225 186 164]
  ...
  [248 235 226]
  [249 232 223]
  [245 228 220]]

 [[223 189 166]
  [222 188 165]
  [222 188 165]
  ...
  [247 234 224]
  [248 231 222]
  [243 227 216]]

 [[227 195 172]
  [225 193 170]
  [223 191 168]
  ...
  [247 234 224]
  [246 230 220]
  [241 226 215]]

 ...

 [[146 154 167]
  [176 184 197]
  [157 165 178]
  ...
  [115 124 137]
  [ 93 100 109]
  [101 108 116]]

 [[121 129 142]
  [140 148 161]
  [140 148 161]
  ...
  [ 82  91 104]
  [157 173 180]
  [128 143 150]]

 [[121 127 138]
  [150 155 167]
  [119 126 137]
  ...
  [132 141 151]
  [154 160 167]
  [119 124 130]]]
[[[226 194 171]
  [227 194 171]
  [227 195 172]
  ...
  [254 250 242]
  [255 250 243]
  [255 247 241]]

 [[227 195 172]
  [226 195 171]
  [227 195 172]
  ...
  [255 251 244]
  [255 247 240]
  [250 240 235]]

 [[227 195 172]
  [228 196 173]
  [228 196 173]
  ...
  [254 247 240]
  [252 242 235]
  [247 236 231]]

 ...

 [[122 130 143]
  [144 152 165]
  [140 148 161]
  ..

[[[ 75  87  83]
  [ 65  69  67]
  [ 57  69  65]
  ...
  [ 22  43  40]
  [ 27  48  45]
  [ 36  56  53]]

 [[109 116 104]
  [ 97 102  86]
  [ 43  57  43]
  ...
  [ 27  48  45]
  [ 40  61  58]
  [ 55  75  72]]

 [[159 168 152]
  [200 207 186]
  [143 161 143]
  ...
  [ 38  59  56]
  [ 37  58  55]
  [ 43  62  59]]

 ...

 [[ 98 100 110]
  [ 84  86  96]
  [ 94 100 110]
  ...
  [162 147 138]
  [ 65  50  42]
  [ 90  76  68]]

 [[103 105 115]
  [123 126 136]
  [105 112 121]
  ...
  [153 138 130]
  [ 98  83  74]
  [ 82  68  60]]

 [[112 114 122]
  [130 132 140]
  [100 106 113]
  ...
  [ 56  40  34]
  [ 73  60  52]
  [103  91  84]]]
[[[ 49  93  84]
  [ 32  71  63]
  [ 54  91  84]
  ...
  [ 38  63  59]
  [ 37  62  58]
  [ 47  71  67]]

 [[ 25  65  57]
  [ 26  61  53]
  [ 85 118 111]
  ...
  [ 30  57  53]
  [ 48  84  78]
  [ 32  67  61]]

 [[ 37  75  67]
  [ 22  55  48]
  [ 25  56  49]
  ...
  [ 42  69  65]
  [ 59 100  93]
  [ 89 128 121]]

 ...

 [[135 141 154]
  [123 130 143]
  [ 94 103 116]
  ..

[[[ 38  69  60]
  [ 32  63  54]
  [ 31  55  53]
  ...
  [ 48  69  70]
  [ 44  68  71]
  [ 36  63  66]]

 [[ 35  66  57]
  [ 36  67  58]
  [ 70  97  87]
  ...
  [ 61  88  89]
  [ 72 108 109]
  [ 97 136 137]]

 [[ 34  65  56]
  [ 46  77  68]
  [ 57  86  71]
  ...
  [ 41  68  69]
  [ 75 110 111]
  [104 145 146]]

 ...

 [[112 118 125]
  [128 134 141]
  [137 147 154]
  ...
  [ 78  62  55]
  [ 57  38  33]
  [ 59  41  37]]

 [[111 117 124]
  [108 114 121]
  [139 149 156]
  ...
  [102  86  79]
  [ 78  60  54]
  [ 68  50  46]]

 [[120 124 129]
  [159 164 169]
  [164 173 178]
  ...
  [ 63  46  41]
  [ 88  72  66]
  [ 79  64  59]]]
[[[ 22  58  49]
  [ 16  53  43]
  [ 29  66  56]
  ...
  [ 49  82  85]
  [ 44  55  58]
  [ 42  62  61]]

 [[ 28  65  55]
  [ 16  53  43]
  [ 22  59  49]
  ...
  [ 70 103 106]
  [ 36  47  49]
  [ 25  44  44]]

 [[ 33  68  58]
  [ 26  61  51]
  [ 23  58  48]
  ...
  [ 14  38  42]
  [ 24  35  38]
  [ 56  76  75]]

 ...

 [[ 98 108 117]
  [105 115 124]
  [125 133 142]
  ..

[[[186 148 130]
  [186 157 137]
  [188 156 137]
  ...
  [236 202 179]
  [237 203 180]
  [237 204 182]]

 [[164 126 108]
  [182 152 133]
  [186 155 136]
  ...
  [236 205 184]
  [237 206 185]
  [237 206 186]]

 [[172 134 116]
  [181 151 132]
  [186 154 135]
  ...
  [238 206 187]
  [239 207 188]
  [238 207 189]]

 ...

 [[ 86  70  63]
  [ 82  66  59]
  [ 96  80  73]
  ...
  [ 74  62  58]
  [ 90  78  74]
  [ 89  77  74]]

 [[ 86  70  63]
  [ 91  75  68]
  [ 76  60  53]
  ...
  [ 88  76  72]
  [ 92  80  76]
  [ 80  68  65]]

 [[109  94  89]
  [104  90  84]
  [ 91  77  71]
  ...
  [ 58  46  44]
  [ 76  64  62]
  [ 69  59  58]]]
[[[182 152 133]
  [183 153 134]
  [183 153 134]
  ...
  [235 199 175]
  [235 199 175]
  [234 199 175]]

 [[184 154 135]
  [184 154 135]
  [184 154 135]
  ...
  [236 199 177]
  [237 200 178]
  [236 200 179]]

 [[185 155 136]
  [183 153 134]
  [184 155 135]
  ...
  [236 202 179]
  [237 203 180]
  [236 202 181]]

 ...

 [[ 75  59  52]
  [ 63  47  40]
  [ 56  40  33]
  ..

[[[182 152 133]
  [183 153 134]
  [183 153 134]
  ...
  [237 203 180]
  [238 204 181]
  [237 203 182]]

 [[182 152 133]
  [183 153 134]
  [183 153 134]
  ...
  [236 202 178]
  [238 204 180]
  [236 203 179]]

 [[182 152 133]
  [183 153 134]
  [183 153 134]
  ...
  [236 202 178]
  [236 202 178]
  [235 202 178]]

 ...

 [[ 86  70  64]
  [ 69  53  48]
  [ 82  66  60]
  ...
  [113 104 101]
  [ 98  89  86]
  [142 134 132]]

 [[ 72  56  50]
  [ 77  61  55]
  [ 97  81  75]
  ...
  [ 74  65  62]
  [ 73  64  61]
  [ 60  51  50]]

 [[ 78  63  60]
  [ 84  69  66]
  [ 89  74  71]
  ...
  [ 88  80  80]
  [ 97  90  89]
  [ 89  82  82]]]
[[[182 152 133]
  [182 152 133]
  [182 152 133]
  ...
  [238 206 186]
  [238 205 185]
  [238 206 186]]

 [[182 152 133]
  [182 152 133]
  [182 152 133]
  ...
  [238 207 184]
  [238 207 184]
  [237 207 185]]

 [[182 152 133]
  [182 152 133]
  [182 152 133]
  ...
  [238 206 183]
  [238 206 183]
  [238 206 184]]

 ...

 [[ 83  67  61]
  [ 82  66  60]
  [ 79  63  57]
  ..

[[[177 143 125]
  [148 105  88]
  [166 121 108]
  ...
  [245 214 193]
  [245 214 193]
  [243 212 192]]

 [[183 149 130]
  [144 102  84]
  [136  92  78]
  ...
  [243 212 191]
  [243 212 191]
  [242 211 191]]

 [[189 155 137]
  [144 102  85]
  [138  93  80]
  ...
  [241 210 189]
  [241 210 189]
  [240 209 189]]

 ...

 [[ 86  70  64]
  [ 87  71  65]
  [ 78  62  56]
  ...
  [ 80  67  59]
  [ 70  58  50]
  [ 39  27  20]]

 [[ 76  60  54]
  [ 78  62  56]
  [ 72  56  50]
  ...
  [ 61  48  40]
  [ 63  50  42]
  [ 66  54  47]]

 [[ 67  52  49]
  [ 69  54  51]
  [ 78  63  60]
  ...
  [ 49  37  31]
  [ 56  44  38]
  [ 49  37  32]]]
