In [13]:
# example of horizontal shift image augmentation
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator

In [14]:
from matplotlib import pyplot
import cv2


In [17]:
import os 

listOfFolderName = []

def search(dirname):
    filenames = os.listdir(dirname)
    for filename in filenames:
        #full_filename = os.path.join(dirname, filename)
        listOfFolderName.append(filename)
        print(filenames)

search("C:/Users/issac/Desktop/")

['2019 Pedestrians Traffic Safety Fact Sheet.pdf', '202005037 이예슬.jpg', '2022_07_ictaes_presentation_Lee_Hwang_Han_최종.pptx', '78798919.png', 'C study', 'desktop.ini', 'hello', 'image.jpeg', 'iMazing2forWindows.exe', 'inside', 'KCI_FI002448301.pdf', 'Lab Room', 'machine_learning', 'outside', 'TRIP2020Larsonetal.pdf', '~$planation of Crosswalk Object Detection Structure.docx', '~WRL1574.tmp', '개발', '대본 초안- 한글.hwp', '도구', '비즈니스 모델 캔버스_202004026_이삭_감정일기.pptx', '서울우수인재', '영어 최종본.hwp', '영어 최종본.pdf', '우수인재 오리엔테이션 배포용.pdf', '이삭', '입사지원서_202004026_이삭.hwp', '자주쓰는거', '총장배 소프트웨어 경진대회 보고서 - 감자 만두들', '퀵 정렬 알고리즘 비교분석_202004026 이삭.pdf', '토익', '학부', '학회']
['2019 Pedestrians Traffic Safety Fact Sheet.pdf', '202005037 이예슬.jpg', '2022_07_ictaes_presentation_Lee_Hwang_Han_최종.pptx', '78798919.png', 'C study', 'desktop.ini', 'hello', 'image.jpeg', 'iMazing2forWindows.exe', 'inside', 'KCI_FI002448301.pdf', 'Lab Room', 'machine_learning', 'outside', 'TRIP2020Larsonetal.pdf', '~$planation of Crosswalk Object De

In [21]:
for foldername in listOfFolderName:
    data_path = 'C:/Users/issac/Desktop/outside/'
    folder = os.listdir(data_path)
    print(folder)

['IMG_3485.png', 'IMG_3486.png', 'IMG_3487.png', 'IMG_3488.png', 'IMG_3489.png', 'IMG_3490.png', 'IMG_3491.png', 'IMG_3492.png', 'IMG_3493.png', 'IMG_3494.png', 'IMG_3495.png', 'IMG_3496.png', 'IMG_3497.png', 'IMG_3498.png', 'IMG_3499.png', 'IMG_3500.png', 'IMG_3501.png', 'IMG_3502.png', 'IMG_3503.png', 'IMG_3504.png', 'IMG_3505.png', 'IMG_3506.png', 'IMG_3507.png', 'IMG_3508.png', 'IMG_3509.png', 'IMG_3510.png', 'IMG_3511.png', 'IMG_3514.png', 'IMG_3515.png', 'IMG_3516.png', 'IMG_3517.png', 'IMG_3518.png', 'IMG_3519.png', 'IMG_3520.png', 'IMG_3521.png', 'IMG_3522.png', 'IMG_3523.png', 'IMG_3524.png', 'IMG_3525.png', 'IMG_3526.png', 'IMG_3527.png', 'IMG_3528.png', 'IMG_3529.png', 'IMG_3530.png', 'IMG_3531.png', 'IMG_3532.png', 'IMG_3533.png', 'IMG_3534.png', 'IMG_3535.png', 'IMG_3536.png', 'IMG_3537.png', 'IMG_3538.png', 'IMG_3539.png', 'IMG_3540.png', 'IMG_3541.png', 'IMG_3542.png', 'IMG_3641.png', 'IMG_3642.png', 'IMG_3643.png', 'IMG_3644.png', 'IMG_3645.png', 'IMG_3646.png', 'IMG_36

In [ ]:
#만들고자하는 갯수
num =9
for file in folder:
    name = file.split(".")[0]
    # load the image
    img = cv2.imread(data_path + name + ".png")
    print(img)
    imageRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # convert to numpy array
    data = img_to_array(img)
    # expand dimension to one sample
    samples = expand_dims(data, 0)
    # create image data augmentation generator
#     datagen = ImageDataGenerator(rotation_range=60, height_shift_range=0.1 )
    datagen = ImageDataGenerator(rotation_range=45, height_shift_range=0.1, width_shift_range=0.1 )

    # prepare iterator
    it = datagen.flow(samples, batch_size=1)
    for i in range(num):   
        batch = it.next()
        # convert to unsigned integers for viewing
        image = batch[0].astype('uint8')
        cv2.imwrite(data_path + name + "test"+ str(i) +".jpg", image)

[[[134 135 115]
  [119 117  99]
  [118 116  98]
  ...
  [196 196 196]
  [191 192 190]
  [193 194 192]]

 [[126 127 107]
  [121 119 101]
  [119 117  99]
  ...
  [194 195 193]
  [180 180 180]
  [185 186 184]]

 [[129 128 108]
  [125 123 105]
  [129 127 109]
  ...
  [193 194 192]
  [186 187 185]
  [183 184 182]]

 ...

 [[125 136 144]
  [126 137 145]
  [ 91 102 110]
  ...
  [128 140 146]
  [129 141 147]
  [134 146 152]]

 [[156 167 175]
  [137 148 156]
  [169 182 190]
  ...
  [114 126 132]
  [154 166 172]
  [ 98 110 116]]

 [[155 166 174]
  [136 145 154]
  [162 175 183]
  ...
  [123 135 141]
  [121 133 139]
  [117 129 135]]]
[[[132 122 104]
  [136 127 107]
  [242 214 190]
  ...
  [193 191 190]
  [197 195 194]
  [201 202 200]]

 [[121 116  99]
  [133 126 107]
  [248 215 196]
  ...
  [191 192 190]
  [165 163 161]
  [196 200 194]]

 [[115 113  95]
  [119 113  95]
  [249 209 197]
  ...
  [190 191 189]
  [184 182 181]
  [202 206 201]]

 ...

 [[140 152 162]
  [150 165 174]
  [138 155 164]
  ..

[[[139 139 125]
  [132 132 118]
  [121 121 107]
  ...
  [232 192 163]
  [232 192 164]
  [234 194 166]]

 [[122 125 109]
  [123 126 110]
  [121 124 108]
  ...
  [233 187 156]
  [232 190 161]
  [233 193 165]]

 [[115 118 103]
  [118 121 105]
  [120 123 107]
  ...
  [235 188 157]
  [231 190 158]
  [233 193 164]]

 ...

 [[163 182 190]
  [172 191 199]
  [ 80  91 101]
  ...
  [183 202 209]
  [139 157 164]
  [139 153 160]]

 [[141 160 168]
  [118 136 145]
  [141 160 168]
  ...
  [131 147 154]
  [161 174 182]
  [181 197 204]]

 [[151 170 178]
  [150 169 177]
  [170 189 197]
  ...
  [129 142 150]
  [144 157 165]
  [211 233 239]]]
[[[120 123 108]
  [127 130 114]
  [129 130 114]
  ...
  [233 193 165]
  [233 194 166]
  [234 194 169]]

 [[115 118 103]
  [130 131 115]
  [126 127 111]
  ...
  [233 187 159]
  [232 191 159]
  [232 192 164]]

 [[113 116 101]
  [124 125 109]
  [129 130 114]
  ...
  [232 186 155]
  [233 189 158]
  [234 192 163]]

 ...

 [[168 185 194]
  [144 161 170]
  [146 167 175]
  ..

[[[ 59  94  84]
  [ 45  88  79]
  [ 51  98  82]
  ...
  [226 232 222]
  [ 14  21  14]
  [ 39  52  50]]

 [[ 35  72  62]
  [ 51  88  79]
  [ 33  41  37]
  ...
  [  9  27  30]
  [ 38  55  56]
  [ 18  23  22]]

 [[ 22  53  44]
  [ 32  68  56]
  [ 34  58  45]
  ...
  [ 74 141 131]
  [ 64  95  91]
  [ 23  34  32]]

 ...

 [[103 110 117]
  [125 134 142]
  [110 116 122]
  ...
  [ 70  55  46]
  [ 79  64  55]
  [ 63  47  40]]

 [[119 126 132]
  [122 125 130]
  [133 143 146]
  ...
  [ 83  67  60]
  [106  92  80]
  [ 80  64  56]]

 [[109 117 124]
  [117 123 130]
  [142 153 157]
  ...
  [ 69  57  47]
  [ 72  60  50]
  [110 100  90]]]
[[[105 179 175]
  [ 64 122 121]
  [ 86 183 179]
  ...
  [118 152 146]
  [248 254 248]
  [252 252 247]]

 [[ 45  94  88]
  [ 78 155 147]
  [ 55 128 125]
  ...
  [ 43  43  49]
  [ 83 138 137]
  [124 166 163]]

 [[ 52  95  86]
  [ 57 103  97]
  [ 67 132 123]
  ...
  [ 29  30  31]
  [ 98 144 141]
  [ 34  66  65]]

 ...

 [[132 135 140]
  [126 132 137]
  [133 139 145]
  ..

[[[ 38  70  65]
  [ 23  93  86]
  [ 25  62  58]
  ...
  [255 252 251]
  [255 255 247]
  [158 129 144]]

 [[154 183 174]
  [ 51  91  79]
  [ 29  65  59]
  ...
  [141  90 104]
  [242 250 243]
  [198 142 154]]

 [[ 41  91  79]
  [ 48  73  69]
  [ 81 129 119]
  ...
  [118 129 131]
  [122 152 149]
  [111  87  90]]

 ...

 [[128 139 143]
  [119 128 135]
  [130 141 147]
  ...
  [ 71  58  50]
  [ 91  78  70]
  [120 105  96]]

 [[152 164 168]
  [142 153 157]
  [120 130 137]
  ...
  [ 78  65  57]
  [173 163 145]
  [ 74  58  51]]

 [[136 139 147]
  [104 110 117]
  [116 122 129]
  ...
  [ 80  67  59]
  [ 91  78  70]
  [ 61  48  40]]]
[[[  7  55  46]
  [ 39  94  85]
  [ 60 109 101]
  ...
  [ 58  58  64]
  [254 255 245]
  [201 205 200]]

 [[ 54  81  77]
  [123 185 177]
  [ 50  95  88]
  ...
  [107 103 105]
  [248 249 239]
  [ 98  97  98]]

 [[ 52  83  74]
  [ 93 132 124]
  [ 46  83  77]
  ...
  [ 56  72  73]
  [ 82 114 113]
  [ 57  75  73]]

 ...

 [[141 152 156]
  [125 132 137]
  [100 106 113]
  ..

[[[165 132 112]
  [163 122 100]
  [225 180 153]
  ...
  [235 193 170]
  [235 194 171]
  [235 197 173]]

 [[165 135 116]
  [161 128 109]
  [226 182 158]
  ...
  [233 192 169]
  [231 190 167]
  [239 198 175]]

 [[168 136 117]
  [164 134 117]
  [227 184 157]
  ...
  [233 194 172]
  [237 196 174]
  [237 199 175]]

 ...

 [[ 59  45  39]
  [ 60  45  42]
  [ 54  39  36]
  ...
  [ 55  43  39]
  [ 46  34  30]
  [ 47  35  31]]

 [[ 53  39  33]
  [ 55  40  36]
  [ 45  33  29]
  ...
  [ 36  24  18]
  [ 62  48  42]
  [ 61  47  41]]

 [[ 68  54  48]
  [ 71  57  51]
  [ 64  37  33]
  ...
  [ 46  34  28]
  [ 51  37  31]
  [ 65  53  47]]]
[[[226 180 156]
  [225 178 150]
  [226 179 152]
  ...
  [246 206 181]
  [247 207 182]
  [245 205 180]]

 [[228 181 155]
  [224 177 149]
  [223 176 148]
  ...
  [240 200 175]
  [237 196 171]
  [235 194 169]]

 [[226 178 150]
  [223 175 147]
  [224 177 149]
  ...
  [238 198 173]
  [238 198 173]
  [237 200 174]]

 ...

 [[ 70  56  50]
  [ 51  37  31]
  [ 97  83  77]
  ..

[[[ 32  50  43]
  [ 37  49  43]
  [ 19  33  22]
  ...
  [148 202 213]
  [158 195 179]
  [162 199 183]]

 [[ 14  35  27]
  [ 23  37  31]
  [ 31  42  32]
  ...
  [158 194 182]
  [158 195 179]
  [160 197 181]]

 [[ 19  33  27]
  [ 41  56  48]
  [  0   4   3]
  ...
  [156 193 185]
  [160 196 180]
  [163 200 184]]

 ...

 [[ 91  74  77]
  [ 83  66  69]
  [102  85  88]
  ...
  [150 127 112]
  [122  98  86]
  [150 125 109]]

 [[106  89  92]
  [105  88  91]
  [ 79  62  65]
  ...
  [117  93  81]
  [126 102  90]
  [139 113 101]]

 [[113  99 103]
  [ 88  73  77]
  [ 90  73  77]
  ...
  [147 127 116]
  [101  76  66]
  [114  88  74]]]
[[[ 44  53  43]
  [ 16  13   7]
  [ 28  22  17]
  ...
  [180 217 201]
  [175 214 199]
  [174 213 198]]

 [[ 13  29  18]
  [ 43  80  62]
  [ 33  39  32]
  ...
  [182 219 203]
  [175 214 199]
  [175 214 199]]

 [[ 46  74  68]
  [ 50  74  64]
  [ 37  54  43]
  ...
  [182 219 203]
  [176 215 200]
  [174 211 195]]

 ...

 [[111  88  92]
  [104  81  86]
  [110  87  92]
  ..

[[[196 232 210]
  [133 172 151]
  [192 211 202]
  ...
  [101 221 196]
  [103 223 198]
  [103 223 198]]

 [[188 214 198]
  [ 36  62  49]
  [ 34  45  39]
  ...
  [102 225 199]
  [101 224 198]
  [101 221 196]]

 [[177 204 184]
  [ 75 104  90]
  [ 45  62  53]
  ...
  [101 224 198]
  [100 223 197]
  [101 221 196]]

 ...

 [[ 73  59  63]
  [ 86  72  76]
  [ 75  61  65]
  ...
  [191 175 169]
  [169 151 144]
  [152 130 123]]

 [[ 76  62  66]
  [ 76  62  66]
  [ 81  66  70]
  ...
  [147 131 125]
  [167 149 142]
  [126 108  99]]

 [[ 80  66  70]
  [ 76  62  66]
  [ 72  58  62]
  ...
  [144 125 120]
  [111  92  87]
  [174 156 145]]]
[[[ 17  48  41]
  [ 34  62  39]
  [ 34  55  47]
  ...
  [104 225 197]
  [101 222 194]
  [100 221 193]]

 [[127 171 150]
  [ 44  73  59]
  [ 27  56  48]
  ...
  [102 223 195]
  [101 222 194]
  [ 99 220 192]]

 [[ 82  92  76]
  [124 162 143]
  [ 50  90  79]
  ...
  [101 222 194]
  [100 221 193]
  [100 221 193]]

 ...

 [[ 74  60  64]
  [ 72  58  62]
  [ 88  74  78]
  ..

[[[ 14  55  40]
  [ 13  56  41]
  [ 19  58  43]
  ...
  [102 231 202]
  [101 230 201]
  [104 233 204]]

 [[  4  30  17]
  [  2  18   5]
  [ 11  47  33]
  ...
  [103 232 203]
  [104 233 204]
  [106 235 206]]

 [[ 15  58  47]
  [ 10  46  34]
  [ 14  55  40]
  ...
  [107 235 206]
  [108 237 208]
  [104 233 204]]

 ...

 [[ 93  72  80]
  [ 91  71  76]
  [ 91  71  76]
  ...
  [101  75  64]
  [103  75  68]
  [114  88  76]]

 [[110  90  95]
  [ 99  79  84]
  [100  79  87]
  ...
  [134 101  90]
  [111  84  74]
  [122  95  85]]

 [[100  80  85]
  [105  85  90]
  [105  84  92]
  ...
  [ 98  71  61]
  [116  91  81]
  [141 110  95]]]
[[[ 18  41  27]
  [  3  27  15]
  [ 94 122 109]
  ...
  [101 226 200]
  [ 97 224 198]
  [ 98 225 199]]

 [[ 13  48  34]
  [ 17  45  32]
  [ 14  42  29]
  ...
  [121 224 201]
  [101 228 202]
  [102 229 203]]

 [[ 81 132 114]
  [ 47  84  70]
  [  5  38  27]
  ...
  [183 231 218]
  [ 99 226 200]
  [101 228 202]]

 ...

 [[ 92  75  78]
  [ 93  78  82]
  [ 76  61  65]
  ..

[[[218 212 193]
  [174 171 167]
  [133 140 133]
  ...
  [ 78 129 132]
  [ 74  90  96]
  [ 13  36  38]]

 [[143 144 135]
  [ 63  70  67]
  [ 38  49  46]
  ...
  [ 63  74  74]
  [194 222 223]
  [176 198 196]]

 [[ 51  66  56]
  [ 94 106 100]
  [107 121 115]
  ...
  [ 48  60  60]
  [ 37  59  60]
  [ 30  51  53]]

 ...

 [[233 245 249]
  [218 231 233]
  [226 241 243]
  ...
  [ 91  73  62]
  [ 86  68  59]
  [129 111 100]]

 [[224 235 239]
  [227 242 244]
  [231 246 248]
  ...
  [ 84  66  55]
  [133 115 104]
  [ 79  61  50]]

 [[226 239 241]
  [216 229 231]
  [219 232 234]
  ...
  [ 88  69  62]
  [105  87  76]
  [ 97  79  68]]]
[[[ 24  45  37]
  [157 144 142]
  [163 154 140]
  ...
  [159 179 180]
  [ 46  75  79]
  [ 50  83  86]]

 [[ 35  58  50]
  [100 106 100]
  [231 243 231]
  ...
  [ 98 125 122]
  [ 78 133 133]
  [ 51  76  84]]

 [[114 150 139]
  [ 37  58  50]
  [ 39  55  46]
  ...
  [ 39  52  50]
  [ 40  45  48]
  [ 97 121 117]]

 ...

 [[223 238 240]
  [229 244 246]
  [211 226 228]
  ..

[[[255 254 250]
  [129  86  89]
  [143 126 117]
  ...
  [122 126 131]
  [ 57  88  89]
  [ 63  91  92]]

 [[251 254 249]
  [245 235 231]
  [255 251 246]
  ...
  [228 223 225]
  [ 51  71  72]
  [108 106 112]]

 [[ 88  66  74]
  [238 228 224]
  [215 217 211]
  ...
  [ 58  58  62]
  [ 99 118 117]
  [ 60  91  91]]

 ...

 [[239 252 254]
  [220 236 235]
  [233 245 245]
  ...
  [174 167 149]
  [117  99  88]
  [ 92  74  63]]

 [[230 242 244]
  [228 241 243]
  [220 233 235]
  ...
  [ 87  67  56]
  [113  93  82]
  [ 87  69  58]]

 [[197 209 211]
  [228 243 245]
  [234 249 251]
  ...
  [ 94  76  65]
  [ 91  73  64]
  [105  87  76]]]
[[[146 128 117]
  [130  96  96]
  [129 105  99]
  ...
  [143 124 127]
  [ 53  47  48]
  [255 254 253]]

 [[182 150 148]
  [228 219 210]
  [255 255 247]
  ...
  [ 63  93  90]
  [218 239 237]
  [ 89 114 115]]

 [[104  80  84]
  [254 247 238]
  [254 254 250]
  ...
  [ 60  85  85]
  [ 43  74  76]
  [ 59  85  85]]

 ...

 [[235 248 250]
  [214 226 228]
  [221 233 235]
  ..